//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicNumberClient.MagicNumberService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MagicNumberService.IMagicNumberService")]
    public interface IMagicNumberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagicNumberService/MagicNumber", ReplyAction="http://tempuri.org/IMagicNumberService/MagicNumberResponse")]
        short MagicNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagicNumberService/MagicNumber", ReplyAction="http://tempuri.org/IMagicNumberService/MagicNumberResponse")]
        System.Threading.Tasks.Task<short> MagicNumberAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMagicNumberServiceChannel : MagicNumberClient.MagicNumberService.IMagicNumberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MagicNumberServiceClient : System.ServiceModel.ClientBase<MagicNumberClient.MagicNumberService.IMagicNumberService>, MagicNumberClient.MagicNumberService.IMagicNumberService {
        
        public MagicNumberServiceClient() {
        }
        
        public MagicNumberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MagicNumberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagicNumberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagicNumberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public short MagicNumber() {
            return base.Channel.MagicNumber();
        }
        
        public System.Threading.Tasks.Task<short> MagicNumberAsync() {
            return base.Channel.MagicNumberAsync();
        }
    }
}
